import type { ProjectScan } from "../types.js";
import {
  hasCommands,
  categorizeFindings,
  enforceTokenBudget,
  filterDiscoverableCommands,
} from "./shared.js";

import type { GenerateOptions } from "./claude.js";

/**
 * Generate an AGENTS.md file from scan results.
 * Used by GitHub Copilot, OpenAI Codex, and other AGENTS.md-aware tools.
 * Format follows the AGENTS.md spec: markdown with directives for agent behavior.
 */
export function generateAgents(scan: ProjectScan, budget: number, options?: GenerateOptions): string {
  const verbose = options?.verbose ?? false;
  const { critical, important, supplementary } = categorizeFindings(scan.findings);

  const sections: { key: string; content: string; priority: number }[] = [];

  sections.push({
    key: "header",
    content: [
      "# AGENTS.md",
      "",
      "Agent instructions for this repository.",
      "Generated by [sourcebook](https://github.com/maroondlabs/sourcebook). Review and edit — the best context comes from human + machine together.",
      "",
    ].join("\n"),
    priority: 100,
  });

  // Commands — strip standard language defaults in non-verbose mode
  const commands = verbose ? scan.commands : filterDiscoverableCommands(scan.commands);
  if (hasCommands(commands)) {
    const lines = ["## Commands", ""];
    if (commands.dev) lines.push(`- **Dev:** \`${commands.dev}\``);
    if (commands.build) lines.push(`- **Build:** \`${commands.build}\``);
    if (commands.test) lines.push(`- **Test:** \`${commands.test}\``);
    if (commands.lint) lines.push(`- **Lint:** \`${commands.lint}\``);
    for (const [name, cmd] of Object.entries(commands)) {
      if (cmd && !["dev", "build", "test", "lint", "start"].includes(name)) {
        lines.push(`- **${name}:** \`${cmd}\``);
      }
    }
    lines.push("");
    sections.push({ key: "commands", content: lines.join("\n"), priority: 95 });
  }

  // Critical constraints as agent directives
  if (critical.length > 0) {
    const lines = [
      "## Constraints",
      "",
      "These constraints MUST be followed when modifying this codebase:",
      "",
    ];
    for (const finding of critical) {
      lines.push(`- **${finding.category}:** ${finding.description}`);
    }
    lines.push("");
    sections.push({ key: "critical", content: lines.join("\n"), priority: 90 });
  }

  // Stack — discoverable from config files, only include in verbose mode
  if (verbose && scan.frameworks.length > 0) {
    sections.push({
      key: "stack",
      content: [
        "## Stack",
        "",
        scan.frameworks.join(", "),
        "",
      ].join("\n"),
      priority: 50,
    });
  }

  // Core modules
  if (scan.rankedFiles && scan.rankedFiles.length > 0) {
    const lines = [
      "## Core Modules (by structural importance)",
      "",
    ];
    for (const { file, score } of scan.rankedFiles.slice(0, 5)) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
    sections.push({ key: "core_modules", content: lines.join("\n"), priority: 60 });
  }

  // Conventions
  if (important.length > 0) {
    const lines = [
      "## Conventions",
      "",
    ];
    for (const finding of important) {
      lines.push(`- **${finding.category}:** ${finding.description}`);
    }
    lines.push("");
    sections.push({ key: "conventions", content: lines.join("\n"), priority: 30 });
  }

  // Additional context
  if (supplementary.length > 0) {
    const lines = ["## Additional Context", ""];
    for (const finding of supplementary) {
      lines.push(`- ${finding.description}`);
    }
    lines.push("");
    sections.push({ key: "supplementary", content: lines.join("\n"), priority: 20 });
  }

  // Manual section prompt
  sections.push({
    key: "manual",
    content: [
      "## What to Add Manually",
      "",
      "The most valuable context is what only you know. Add:",
      "",
      "- Architectural decisions and why they were made",
      "- Past incidents that shaped current conventions",
      "- Deprecated patterns to avoid in new code",
      "- Domain-specific rules or terminology",
      "- Environment setup beyond what .env.example shows",
      "",
    ].join("\n"),
    priority: 10,
  });

  const kept = enforceTokenBudget(sections, budget);
  return kept.join("\n");
}
