import type { ProjectScan } from "../types.js";
import {
  isCritical,
  groupByCategory,
  hasCommands,
  categorizeFindings,
  enforceTokenBudget,
} from "./shared.js";

/**
 * Generate a CLAUDE.md file from scan results.
 *
 * Design principles (from research):
 * 1. ONLY non-discoverable information (ETH Zurich: auto-generated obvious context hurts by 2-3%)
 * 2. Context-rot-aware formatting (Chroma Research: 30%+ accuracy drop for info in the middle)
 *    → Critical info at BEGINNING and END of file
 * 3. Karpathy's program.md pattern: constraints, gotchas, and autonomy boundaries
 */
export function generateClaude(scan: ProjectScan, budget: number): string {
  const { critical, important, supplementary } = categorizeFindings(scan.findings);

  const sections: { key: string; content: string; priority: number }[] = [];

  // ============================================
  // BEGINNING: Most critical info goes here
  // (LLMs retain start of context best)
  // ============================================

  const header = [
    "# CLAUDE.md",
    "",
    "This file provides guidance to Claude Code when working with this codebase.",
    "Generated by [sourcebook](https://github.com/maroondlabs/sourcebook). Review and edit — the best context comes from human + machine together.",
    "",
  ].join("\n");
  sections.push({ key: "header", content: header, priority: 100 });

  // Commands first -- most immediately actionable
  if (hasCommands(scan.commands)) {
    const lines = ["## Commands", ""];
    if (scan.commands.dev) lines.push(`- **Dev:** \`${scan.commands.dev}\``);
    if (scan.commands.build) lines.push(`- **Build:** \`${scan.commands.build}\``);
    if (scan.commands.test) lines.push(`- **Test:** \`${scan.commands.test}\``);
    if (scan.commands.lint) lines.push(`- **Lint:** \`${scan.commands.lint}\``);
    for (const [name, cmd] of Object.entries(scan.commands)) {
      if (cmd && !["dev", "build", "test", "lint", "start"].includes(name)) {
        lines.push(`- **${name}:** \`${cmd}\``);
      }
    }
    lines.push("");
    sections.push({ key: "commands", content: lines.join("\n"), priority: 95 });
  }

  // Critical warnings/constraints near the top
  if (critical.length > 0) {
    const lines = ["## Critical Constraints", ""];
    for (const finding of critical) {
      lines.push(`- **${finding.category}:** ${finding.description}`);
    }
    lines.push("");
    sections.push({ key: "critical", content: lines.join("\n"), priority: 90 });
  }

  // ============================================
  // MIDDLE: Less critical but useful info
  // (LLMs retain this worst -- keep it short)
  // ============================================

  // Stack (brief)
  if (scan.frameworks.length > 0) {
    const content = ["## Stack", "", scan.frameworks.join(", "), ""].join("\n");
    sections.push({ key: "stack", content, priority: 50 });
  }

  // Key directories (only non-obvious ones)
  if (Object.keys(scan.structure.directories).length > 0) {
    const nonObvious = Object.entries(scan.structure.directories).filter(
      ([dir]) => !["src", "public", "node_modules", "dist", "build"].includes(dir)
    );
    if (nonObvious.length > 0) {
      const lines = ["## Project Structure", ""];
      for (const [dir, purpose] of nonObvious) {
        lines.push(`- \`${dir}/\` — ${purpose}`);
      }
      lines.push("");
      sections.push({ key: "structure", content: lines.join("\n"), priority: 40 });
    }
  }

  // Core modules (from PageRank)
  if (scan.rankedFiles && scan.rankedFiles.length > 0) {
    const top5 = scan.rankedFiles.slice(0, 5);
    const lines = ["## Core Modules (by structural importance)", ""];
    for (const { file } of top5) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
    sections.push({ key: "core_modules", content: lines.join("\n"), priority: 60 });
  }

  // Important findings (high confidence, non-critical)
  if (important.length > 0) {
    const lines = ["## Conventions & Patterns", ""];
    const grouped = groupByCategory(important);
    for (const [category, findings] of grouped) {
      if (findings.length === 1) {
        lines.push(`- **${category}:** ${findings[0].description}`);
      } else {
        lines.push(`- **${category}:**`);
        for (const f of findings) {
          lines.push(`  - ${f.description}`);
        }
      }
    }
    lines.push("");
    sections.push({ key: "conventions", content: lines.join("\n"), priority: 30 });
  }

  // Supplementary findings (medium confidence)
  if (supplementary.length > 0) {
    const lines = ["## Additional Context", ""];
    const grouped = groupByCategory(supplementary);
    for (const [category, findings] of grouped) {
      if (findings.length === 1) {
        lines.push(`- **${category}:** ${findings[0].description}`);
      } else {
        lines.push(`- **${category}:**`);
        for (const f of findings) {
          lines.push(`  - ${f.description}`);
        }
      }
    }
    lines.push("");
    sections.push({ key: "supplementary", content: lines.join("\n"), priority: 20 });
  }

  // ============================================
  // END: Important reminders go here
  // (LLMs retain end of context second-best)
  // ============================================

  const footer = [
    "## What to Add Manually",
    "",
    "The most valuable context is what only you know. Add:",
    "",
    "- Architectural decisions and why they were made",
    "- Past incidents that shaped current conventions",
    "- Deprecated patterns to avoid in new code",
    "- Domain-specific rules or terminology",
    "- Environment setup beyond what .env.example shows",
    "",
  ].join("\n");
  sections.push({ key: "footer", content: footer, priority: 90 });

  // Apply smart budget enforcement
  const kept = enforceTokenBudget(sections, budget);
  return kept.join("\n");
}
