import type { ProjectScan, Finding } from "../types.js";

/**
 * Generate a CLAUDE.md file from scan results.
 *
 * Design principles (from research):
 * 1. ONLY non-discoverable information (ETH Zurich: auto-generated obvious context hurts by 2-3%)
 * 2. Context-rot-aware formatting (Chroma Research: 30%+ accuracy drop for info in the middle)
 *    → Critical info at BEGINNING and END of file
 * 3. Karpathy's program.md pattern: constraints, gotchas, and autonomy boundaries
 */
export function generateClaude(scan: ProjectScan, budget: number): string {
  // Separate findings by importance for context-rot-aware placement
  const critical = scan.findings.filter(
    (f) => f.confidence === "high" && isCritical(f)
  );
  const important = scan.findings.filter(
    (f) => f.confidence === "high" && !isCritical(f)
  );
  const supplementary = scan.findings.filter(
    (f) => f.confidence === "medium"
  );

  const sections: string[] = [];

  // ============================================
  // BEGINNING: Most critical info goes here
  // (LLMs retain start of context best)
  // ============================================

  sections.push("# CLAUDE.md");
  sections.push("");
  sections.push(
    "This file provides guidance to Claude Code when working with this codebase."
  );
  sections.push(
    "Generated by [sourcebook](https://github.com/maroondlabs/sourcebook). Review and edit — the best context comes from human + machine together."
  );
  sections.push("");

  // Commands first -- most immediately actionable
  if (hasCommands(scan.commands)) {
    sections.push("## Commands");
    sections.push("");
    if (scan.commands.dev) sections.push(`- **Dev:** \`${scan.commands.dev}\``);
    if (scan.commands.build)
      sections.push(`- **Build:** \`${scan.commands.build}\``);
    if (scan.commands.test)
      sections.push(`- **Test:** \`${scan.commands.test}\``);
    if (scan.commands.lint)
      sections.push(`- **Lint:** \`${scan.commands.lint}\``);
    for (const [name, cmd] of Object.entries(scan.commands)) {
      if (cmd && !["dev", "build", "test", "lint", "start"].includes(name)) {
        sections.push(`- **${name}:** \`${cmd}\``);
      }
    }
    sections.push("");
  }

  // Critical warnings/constraints near the top (danger zone, fragile code, hidden deps)
  if (critical.length > 0) {
    sections.push("## Critical Constraints");
    sections.push("");
    for (const finding of critical) {
      sections.push(`- **${finding.category}:** ${finding.description}`);
    }
    sections.push("");
  }

  // ============================================
  // MIDDLE: Less critical but useful info
  // (LLMs retain this worst -- keep it short)
  // ============================================

  // Stack (brief)
  if (scan.frameworks.length > 0) {
    sections.push("## Stack");
    sections.push("");
    sections.push(scan.frameworks.join(", "));
    sections.push("");
  }

  // Key directories (only non-obvious ones)
  if (Object.keys(scan.structure.directories).length > 0) {
    const nonObvious = Object.entries(scan.structure.directories).filter(
      ([dir]) =>
        !["src", "public", "node_modules", "dist", "build"].includes(dir)
    );

    if (nonObvious.length > 0) {
      sections.push("## Project Structure");
      sections.push("");
      for (const [dir, purpose] of nonObvious) {
        sections.push(`- \`${dir}/\` — ${purpose}`);
      }
      sections.push("");
    }
  }

  // Core modules (from PageRank)
  if (scan.rankedFiles && scan.rankedFiles.length > 0) {
    const top5 = scan.rankedFiles.slice(0, 5);
    sections.push("## Core Modules (by structural importance)");
    sections.push("");
    for (const { file } of top5) {
      sections.push(`- \`${file}\``);
    }
    sections.push("");
  }

  // Important findings (high confidence, non-critical)
  if (important.length > 0) {
    sections.push("## Conventions & Patterns");
    sections.push("");
    const grouped = groupByCategory(important);
    for (const [category, findings] of grouped) {
      if (findings.length === 1) {
        sections.push(`- **${category}:** ${findings[0].description}`);
      } else {
        sections.push(`- **${category}:**`);
        for (const f of findings) {
          sections.push(`  - ${f.description}`);
        }
      }
    }
    sections.push("");
  }

  // Supplementary findings (medium confidence)
  if (supplementary.length > 0) {
    sections.push("## Additional Context");
    sections.push("");
    const grouped = groupByCategory(supplementary);
    for (const [category, findings] of grouped) {
      if (findings.length === 1) {
        sections.push(`- **${category}:** ${findings[0].description}`);
      } else {
        sections.push(`- **${category}:**`);
        for (const f of findings) {
          sections.push(`  - ${f.description}`);
        }
      }
    }
    sections.push("");
  }

  // ============================================
  // END: Important reminders go here
  // (LLMs retain end of context second-best)
  // ============================================

  // "What to add" section -- prompts human to add non-discoverable context
  sections.push("## What to Add Manually");
  sections.push("");
  sections.push(
    "The most valuable context is what only you know. Add:"
  );
  sections.push("");
  sections.push("- Architectural decisions and why they were made");
  sections.push(
    "- Past incidents that shaped current conventions"
  );
  sections.push("- Deprecated patterns to avoid in new code");
  sections.push("- Domain-specific rules or terminology");
  sections.push("- Environment setup beyond what .env.example shows");
  sections.push("");

  let output = sections.join("\n");

  // Token budget enforcement (rough: 1 token ≈ 4 chars)
  const charBudget = budget * 4;
  if (output.length > charBudget) {
    output = output.slice(0, charBudget);
    const lastNewline = output.lastIndexOf("\n");
    output =
      output.slice(0, lastNewline) +
      "\n\n<!-- truncated to fit token budget -->\n";
  }

  return output;
}

/**
 * Determine if a finding is "critical" -- things that can cause real damage
 * if an agent gets them wrong. These go at the TOP of the file.
 */
function isCritical(finding: Finding): boolean {
  const criticalCategories = new Set([
    "Hidden dependencies",
    "Circular dependencies",
    "Core modules",
    "Fragile code",
    "Git history",
    "Commit conventions",
  ]);

  const criticalKeywords = [
    "breaking",
    "blast radius",
    "deprecated",
    "don't",
    "must",
    "never",
    "revert",
    "fragile",
    "hidden",
    "invisible",
    "coupling",
  ];

  if (criticalCategories.has(finding.category)) return true;

  const desc = finding.description.toLowerCase();
  return criticalKeywords.some((kw) => desc.includes(kw));
}

function groupByCategory(
  findings: Finding[]
): Map<string, Finding[]> {
  const grouped = new Map<string, Finding[]>();
  for (const finding of findings) {
    const existing = grouped.get(finding.category) || [];
    existing.push(finding);
    grouped.set(finding.category, existing);
  }
  return grouped;
}

function hasCommands(commands: Record<string, string | undefined>): boolean {
  return Object.values(commands).some((v) => v !== undefined);
}
