import type { ProjectScan } from "../types.js";
import {
  hasCommands,
  categorizeFindings,
  enforceTokenBudget,
} from "./shared.js";

/**
 * Generate GitHub Copilot instructions from scan results.
 * Outputs .github/copilot-instructions.md — conversational style.
 */
export function generateCopilot(scan: ProjectScan, budget: number): string {
  const { critical, important, supplementary } = categorizeFindings(scan.findings);

  const sections: { key: string; content: string; priority: number }[] = [];

  sections.push({
    key: "header",
    content: [
      "# Copilot Instructions",
      "",
      "These instructions were generated by [sourcebook](https://github.com/maroondlabs/sourcebook). Review and edit — the best context comes from human + machine together.",
      "",
    ].join("\n"),
    priority: 100,
  });

  // Commands
  if (hasCommands(scan.commands)) {
    const lines = ["## Development Commands", ""];
    if (scan.commands.dev) lines.push(`- Dev server: \`${scan.commands.dev}\``);
    if (scan.commands.build) lines.push(`- Build: \`${scan.commands.build}\``);
    if (scan.commands.test) lines.push(`- Tests: \`${scan.commands.test}\``);
    if (scan.commands.lint) lines.push(`- Lint: \`${scan.commands.lint}\``);
    for (const [name, cmd] of Object.entries(scan.commands)) {
      if (cmd && !["dev", "build", "test", "lint", "start"].includes(name)) {
        lines.push(`- ${name}: \`${cmd}\``);
      }
    }
    lines.push("");
    sections.push({ key: "commands", content: lines.join("\n"), priority: 95 });
  }

  // Critical constraints
  if (critical.length > 0) {
    const lines = [
      "## Important Constraints",
      "",
      "Follow these rules when modifying this codebase:",
      "",
    ];
    for (const finding of critical) {
      lines.push(`- ${finding.description}`);
    }
    lines.push("");
    sections.push({ key: "critical", content: lines.join("\n"), priority: 90 });
  }

  // Stack
  if (scan.frameworks.length > 0) {
    sections.push({
      key: "stack",
      content: [
        "## Technology Stack",
        "",
        `This project uses: ${scan.frameworks.join(", ")}.`,
        "",
      ].join("\n"),
      priority: 50,
    });
  }

  // Core modules
  if (scan.rankedFiles && scan.rankedFiles.length > 0) {
    const lines = [
      "## High-Impact Files",
      "",
      "These files are imported by many others. Changes here have wide blast radius:",
      "",
    ];
    for (const { file } of scan.rankedFiles.slice(0, 5)) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
    sections.push({ key: "core_modules", content: lines.join("\n"), priority: 60 });
  }

  // Conventions
  if (important.length > 0) {
    const lines = [
      "## Code Conventions",
      "",
      "This project follows these patterns:",
      "",
    ];
    for (const finding of important) {
      lines.push(`- ${finding.description}`);
    }
    lines.push("");
    sections.push({ key: "conventions", content: lines.join("\n"), priority: 30 });
  }

  // Additional context
  if (supplementary.length > 0) {
    const lines = ["## Additional Notes", ""];
    for (const finding of supplementary) {
      lines.push(`- ${finding.description}`);
    }
    lines.push("");
    sections.push({ key: "supplementary", content: lines.join("\n"), priority: 20 });
  }

  const kept = enforceTokenBudget(sections, budget);
  return kept.join("\n");
}
