import type { ProjectScan, Finding } from "../types.js";

/**
 * Generate GitHub Copilot instructions from scan results.
 *
 * Copilot supports:
 * - `.github/copilot-instructions.md` — repo-level instructions (always loaded)
 * - `.instructions.md` — per-directory instructions (loaded when files in that dir are referenced)
 *
 * We generate the repo-level file. Copilot's format is plain markdown with
 * natural language instructions — more conversational than Cursor's directive style.
 */
export function generateCopilot(scan: ProjectScan, budget: number): string {
  const critical = scan.findings.filter(
    (f) => f.confidence === "high" && isCritical(f)
  );
  const important = scan.findings.filter(
    (f) => f.confidence === "high" && !isCritical(f)
  );
  const supplementary = scan.findings.filter(
    (f) => f.confidence === "medium"
  );

  const sections: string[] = [];

  sections.push("# Copilot Instructions");
  sections.push("");
  sections.push(
    "These instructions were generated by [sourcebook](https://github.com/maroondlabs/sourcebook). Review and edit — the best context comes from human + machine together."
  );
  sections.push("");

  // Commands
  if (hasCommands(scan.commands)) {
    sections.push("## Development Commands");
    sections.push("");
    if (scan.commands.dev) sections.push(`- Dev server: \`${scan.commands.dev}\``);
    if (scan.commands.build) sections.push(`- Build: \`${scan.commands.build}\``);
    if (scan.commands.test) sections.push(`- Tests: \`${scan.commands.test}\``);
    if (scan.commands.lint) sections.push(`- Lint: \`${scan.commands.lint}\``);
    for (const [name, cmd] of Object.entries(scan.commands)) {
      if (cmd && !["dev", "build", "test", "lint", "start"].includes(name)) {
        sections.push(`- ${name}: \`${cmd}\``);
      }
    }
    sections.push("");
  }

  // Critical constraints
  if (critical.length > 0) {
    sections.push("## Important Constraints");
    sections.push("");
    sections.push("Follow these rules when modifying this codebase:");
    sections.push("");
    for (const finding of critical) {
      sections.push(`- ${finding.description}`);
    }
    sections.push("");
  }

  // Stack
  if (scan.frameworks.length > 0) {
    sections.push("## Technology Stack");
    sections.push("");
    sections.push(`This project uses: ${scan.frameworks.join(", ")}.`);
    sections.push("");
  }

  // Core modules
  if (scan.rankedFiles && scan.rankedFiles.length > 0) {
    const top5 = scan.rankedFiles.slice(0, 5);
    sections.push("## High-Impact Files");
    sections.push("");
    sections.push("These files are imported by many others. Changes here have wide blast radius:");
    sections.push("");
    for (const { file } of top5) {
      sections.push(`- \`${file}\``);
    }
    sections.push("");
  }

  // Conventions
  if (important.length > 0) {
    sections.push("## Code Conventions");
    sections.push("");
    sections.push("This project follows these patterns:");
    sections.push("");
    for (const finding of important) {
      sections.push(`- ${finding.description}`);
    }
    sections.push("");
  }

  // Additional context
  if (supplementary.length > 0) {
    sections.push("## Additional Notes");
    sections.push("");
    for (const finding of supplementary) {
      sections.push(`- ${finding.description}`);
    }
    sections.push("");
  }

  let output = sections.join("\n");

  // Token budget enforcement
  const charBudget = budget * 4;
  if (output.length > charBudget) {
    output = output.slice(0, charBudget);
    const lastNewline = output.lastIndexOf("\n");
    output = output.slice(0, lastNewline) + "\n";
  }

  return output;
}

function isCritical(finding: Finding): boolean {
  const criticalCategories = new Set([
    "Hidden dependencies",
    "Circular dependencies",
    "Core modules",
    "Fragile code",
    "Git history",
    "Commit conventions",
  ]);

  const criticalKeywords = [
    "breaking", "blast radius", "deprecated", "don't", "must",
    "never", "revert", "fragile", "hidden", "invisible", "coupling",
  ];

  if (criticalCategories.has(finding.category)) return true;
  const desc = finding.description.toLowerCase();
  return criticalKeywords.some((kw) => desc.includes(kw));
}

function hasCommands(commands: Record<string, string | undefined>): boolean {
  return Object.values(commands).some((v) => v !== undefined);
}
